### PR TITLE
JavaScript error on my Steam Deck!!!!

### PR DESCRIPTION
**Pull request by WillRRRR**
I tried use Wine-GE-Proton7-15-SC and got error!

### CODE REVIEW

**Comment by WillRRRR** [comment]
IMG_1270

**Comment by WillRRRR** [comment]
I tried play Star Citizen on my Steam Deck and got error. :-(

**Comment by dPing** [comment]
> I tried play Star Citizen on my Steam Deck and got error. :-(

You should download the LUG helper. Let me know if you need a link. 7-15-SC is not longer a current version but you can use the latest GE runner without issues as long as you either apply the EAC patch ( via lug helper) or install SC with Lutris which will use a current version of GE runner and apply the patch via lutris script.

**Comment by dPing** [comment]
https://github.com/starcitizen-lug/lug-helper or 8f you have arch (since you are on steam deck you are on arch by default) search for lug helper in the AUR

**Comment by dPing** [comment]
LUG also maintains a wiki and a discord which will help you along the way

https://github.com/starcitizen-lug/knowledge-base

https://discord.gg/meCFYPj

**Comment by GloriousEggroll** [comment]
Please note that the pull requests section of this github is NOT the place to report issues. Issues on this github repo are intentionally closed for a reason. As mentioned we request that you use discord.

As additionally noted this issue is resolved in the LUG knowledgebase. closing.

**Pull request closed without merging**
